<h3 class="page-header">图片管理</h3>
<?php foreach ($this->paginator as $img){?>
<div class="col-lg-3">
<img src="<?php echo SITE_BASE_URL.'/images/resources/'.$img['path']?>" alt="<?php echo $img['text']?>" class="img-thumbnail">
</div>
<?php }?>
<div class="clearfix"></div>


<div id="article-footinfo-area" class="clearfix">
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'my_pagination_control.phtml'); ?>
</div>