<style type="text/css">
<!--
.bookinfo{margin-bottom: 20px}
.bookinfo img{width: 700px}
.bookinfo .hbtn{position:absolute; bottom:0; padding:5px; display:none;}

-->
</style>
<div class="col-md-12">
<div id="myCarousel" class="carousel slide" data-interval="5000" data-ride="carousel">
<!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

<!-- Carousel items -->
<div class="carousel-inner">
    <div class="item active">
    <img src="<?php echo SITE_BASE_URL?>/images/bg.jpg" alt="First1 slide">
    <div class="carousel-caption">
    <p>11111111</p>
    <p>11111111</p>
    <p>11111111</p>
    <p>11111111</p>
    <p>11111111</p>
    </div>
    </div>
    <div class="item">
    <img data-src="holder.js/900x380/auto/#666:#7a7a7a/text:First2 slide" alt="First1 slide">
    <div class="carousel-caption">
    <p>2222222</p>
    <p>2222222</p>
    <p>2222222</p>
    <p>2222222</p>
    <p>2222222</p>
    <p>2222222</p>
    </div>
    </div>
</div>
<!-- Carousel nav -->
<a class="carousel-control left" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
</a>
<a class="carousel-control right" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
</a>
</div>
</div>
<?php if(count($this->bookList)>0){?>
<?php foreach ($this->bookList as $book){?>
<div class="col-lg-3 col-md-4 col-sm-6 bookinfo"><a href="<?php echo SITE_BASE_URL.'/pdf/'.$book['path'] ?>"><img class="img-thumbnail img-responsive" src="<?php echo SITE_BASE_URL.'/pdf/'.$book['cover_path'] ?>"/></a>
<div class="hbtn"><a href="<?php echo SITE_BASE_URL.'/book/detail?bid='.$book['id']?>" class="btn btn-default">查看详细内容</a></div>
</div>
<?php }?>
<?php }?>

<script type="text/javascript" src="<?php echo SITE_BASE_URL?>/js/holder.js"></script>
<script type="text/javascript">
$(function(){
	$('.bookinfo').bind('mouseover',function(){
		$(this).children('.hbtn').show();
	});
	$('.bookinfo').bind('mouseout',function(){
		$(this).children('.hbtn').hide();
	});
	
})
</script>