<?php if ($this->pageCount): ?>
<div class="paginationControl">
<ul class="pagination">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <li><a href="#" onclick="changePage(<?php echo $this->previous?>)">
    &lt; 前一页
  </a></li>
<?php else: ?>
  <li class="disabled"><span>&lt; 前一页</span></li>
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li><a href="#" onclick="changePage(<?php echo $page ?>)">
        <?php echo $page; ?>
    </a></li>
  <?php else: ?>
    <li class="active"><span><?php echo $page; ?></span></li>
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li><a href="#" id="nextpage" onclick="changePage(<?php echo $this->next?>)">
    后一页  &gt;
  </a></li>
<?php else: ?>
  <li  class="disabled"><span>后一页 &gt;</span></li>
<?php endif; ?>
</ul>
</div>
<?php endif; ?>