<style>
<!--
.zend_form{overflow: hidden;}
#loginBtn{width: 100%}

#loginForm{width: 498px; overflow: hidden; border:solid 1px #cccccc; position: relative;}
#loginFormContainer{width: 500px; margin: 90px auto}
#loginForm h4{height: 50px; line-height: 50px; margin: 5px 20px 10px}
#loginForm .zend_form{margin: 5px 0}
#loginForm .zend_form dd{margin:5px 40px}
//#userName,#userPassword{height: 25px; line-height: 25px; width: 250px}
#captcha-element{position:relative;}
#captcha-input{width: 210px; position: absolute; top:0px; right:0px}
#loginForm #submit{width: 260px; margin: 0 auto; display: block; height: 38px; line-height: 38px}
#userRegist{margin:0 40px 20px; height: 35px; line-height: 35px}
#userRegist .btn-primary{margin-right: 14px; width: 25%}

-->
</style>
<div id="loginFormContainer">
	<div id="loginForm">
		<h4 class="page-header">管理员登录</h4>
		<?php if(isset($this->authErrorMessage)){?>
			<p class="authError"><?php echo $this->authErrorMessage?></p>
		<?php }?>
		<?php echo $this->form?>
	</div>
</div>
<script type="text/javascript" src="<?php echo SITE_BASE_URL?>/js/jquery-1.10.2.min.js" language="javascript" ></script>
<script type="text/javascript">
    $(document).ready(function(){
        //给验证码图片绑定点击事件
        $("#captcha-element img").bind("click",function(){ 
            $.ajax({
                type: "GET",   
                url: "<?php echo SITE_BASE_URL?>/login/refresh-captcha",
                success: refreshCaptcha,
                error: error
            })
        })
    });

    function refreshCaptcha(data){
        var src="<?php echo SITE_BASE_URL?>/images/captcha/"+data+".png";
        //更新图片
        $("#captcha-element img").attr('src',src);
        //更新隐藏元素的id值
        $("#captcha-id").attr('value',data);
    }
    function error(){
        alert('error');
    }
</script>











