<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>涂色-管理中心</title>
    <link href="<?php echo $this->baseUrl()?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl()?>/css/dashboard.css" rel="stylesheet">
    <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/jquery-1.10.2.min.js"></script>
	<!--[if lt IE 9]>
    <script src="<?php echo SITE_BASE_URL?>/js/html5shiv.js"></script>
    <script src="<?php echo SITE_BASE_URL?>/js/respond.min.js"></script>
	<![endif]-->
</head>
<body>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">涂色管理中心</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
        </div>
      </div>
    </div>
    
      <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="<?php echo SITE_BASE_URL.'/admin/'?>">图片管理</a></li>
            <li><a href="<?php echo SITE_BASE_URL.'/admin/img-upload/'?>">图品上传</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="<?php echo SITE_BASE_URL.'/admin/book/'?>">图书管理</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="<?php echo SITE_BASE_URL.'/admin/imgcat/'?>">图片类别</a></li>
            <li><a href="<?php echo SITE_BASE_URL.'/admin/imgcat/addcat/'?>">添加主类</a></li>
            <li><a href="<?php echo SITE_BASE_URL.'/admin/imgcat/addcatdetail/'?>">添加类别明细</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        	
            <?php if(isset($this->fbmsg)){?>
            <div id="fbmsg" class="alert <?php echo $this->fbmsg['type']?> fade in">
            	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <span id="notifyMessage"><?php echo $this->fbmsg['msg']?></span>
            </div>
            <?php }?>
        	
                <?php echo $this->layout()->content; ?>
            
            
    	</div>
    </div>
    </div>


    <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/bootstrap.min.js"></script>
</body>
</html>