<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>涂色</title>
    <link href="<?php echo $this->baseUrl()?>/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <h1>Hello, world!</h1>
    <?php echo $this->layout()->content; ?>

    <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/bootstrap.min.js"></script>
</body>
</html>