<style type="text/css">
<!--
-->
</style>
<h3 class="page-header">完善图片信息</h3>
<div class="col-sm-4">
<img src="<?php echo SITE_BASE_URL.'/temp/'.$this->img?>" width="280px" />
</div>
<div class="col-sm-8">
<?php echo $this->form ?>
<?php if(count($this->cats)>0){?>
<ul class="nav nav-tabs" id="myTab">
<?php 
    $i=0;
    foreach($this->cats as $cat){
	    if(0==$i){
	        echo '<li class="active"><a data-toggle="tab" href="fl'.$cat['id'].'">'.$cat['name'].'</a></li>';
	    }else{
	        echo '<li><a data-toggle="tab" href="fl'.$cat['id'].'">'.$cat['name'].'</a></li>';
	    }
	    $i++;
    }
?>
</ul>
<div class="tab-content" id="myTabContent">
	<?php
	    $m=0; 
	    foreach ($this->catDetails as $key=>$values){ 
			if(0==$m){
			    echo '<div id="fl'.$key.'" class="tab-pane fade in active">';
			}else{
			    echo '<div id="fl'.$key.'" class="tab-pane fade">';
			}
			
			foreach($values as $value){
			    echo '<span>'.$value.'</span>';
			}
            echo '</div>';
	        $m++;
	    }
	?>
</div>
<?php }?>
</div>
<script type="text/javascript">
$('#myTab a').click(function (e) {
	  e.preventDefault()
	  $(this).tab('show')
	})

</script>
